apiVersion: v1
kind: Service
metadata:
  name: nodered-node-port
spec:
  type: NodePort
  ports:
    - port: 8086
      targetPort: 8086
      nodePort: 30001
  selector:
    component: web