apiVersion: v1
kind: Service
metadata:
  name: nodered-node-port
spec:
  type: NodePort
  ports:
    - name: nodered
      port: 1880
      targetPort: 1880
      nodePort: 30000
    - name: grafana
      port: 3000
      targetPort: 3000
      nodePort: 30002
    - name: influxdb
      port: 8086
      targetPort: 8086
      nodePort: 30001
  selector:
    component: web
