apiVersion: v1
kind: Pod
metadata:
  name: nodered
  labels:
    component: web
spec:
  containers:
    - name: nodered
      image: girthquake1/infrastructure_nodered
      ports:
        - containerPort: 1880
