apiVersion: v1
kind: Service
metadata:
  name: nodered-node-port
spec:
  type: NodePort
  ports:
    - port: 1880
      targetPort: 1880
      nodePort: 30000
  selector:
    component: web