{
 "title": "New dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "kills",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"lolbucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"stats\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"kills\")\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "gold",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"lolbucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"stats\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"gold\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "deaths",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "query": "from(bucket: \"lolbucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"stats\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"deaths\")\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "damage dealt",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "query": "from(bucket: \"lolbucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"stats\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"damageToChampions\")\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "damageTaken",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "query": "from(bucket: \"lolbucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"stats\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"damageTaken\")\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "damage mitigated",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "query": "from(bucket: \"lolbucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"stats\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"damageMitigated\")\r\n  |> yield(name: \"mean\")"
    }
   ]
  }
 ]
}